name: livekit_pip_android
description: Android implementation of the livekit_pip plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0

flutter:
  plugin:
    implements: livekit_pip
    platforms:
      android:
        package: dev.kaffah
        pluginClass: PipPlugin
        dartPluginClass: LivekitPipAndroid

dependencies:
  flutter:
    sdk: flutter
  livekit_pip_platform_interface:
    path: ../livekit_pip_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  pigeon: ^27.1.0
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
